### PR TITLE
Add sealed keyword to Nothing singleton.

### PR DESCRIPTION
**Pull request by dedale**
I think we can explicitely close this class with the sealed keyword.

### CODE REVIEW

**Comment by Stephanvs** [comment]
Nothing can ultimately come from nothing..

**Comment by dsyme** [comment]
@dedale For better or worse it seems nothing came of this

**Comment by dedale** [comment]
:rofl:

**Comment by gregoryyoung** [comment]
LOL @dsyme

**Comment by bartelink** [comment]
@dedale What have you lost? Nothing

**Pull request closed without merging**
